version: "{branch}-{build}"

max_jobs: 1

environment:
 PY_PYTHON: 3.7-32

init:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG_NAME) {
        if ($env:APPVEYOR_REPO_TAG_NAME.EndsWith("-dev")) {
          Set-AppveyorBuildVariable -Name "prerelease" -Value "tru"
        } else {
          Set-AppveyorBuildVariable -Name "prerelease" -Value "false"
        }
      }

install:
  - py -m pip install markdown
  - py -m pip install scons

build_script:
  - set path=%path%;C:\Python37\Scripts
  - scons
  - scons pot

artifacts:
  - path: '*.nvda-addon'
    name: addon
    type: application/x-nvda-addon
  - path: '*.pot'
    type: application/x-pot
    
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: ayZmtkNXgFmwTjA6LMI7/cCcFVAL9w7IiKuCOFeegjntytcAOY8Wzb2LAX2ZqKgY
  artifact: addon
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
    
#deploy:
#  release: $(APPVEYOR_REPO_TAG_NAME)
#  description: $(APPVEYOR_REPO_TAG_NAME)
#  provider: GitHub
#  auth_token:
#    secure: ayZmtkNXgFmwTjA6LMI7/cCcFVAL9w7IiKuCOFeegjntytcAOY8Wzb2LAX2ZqKgY
#  artifact: addon
#  draft: false
#  prerelease: $(prerelease)
#  on:
#    appveyor_repo_tag: true        # deploy on tag push only
#    branch: /stable/
